### ISSUE TITLE
Show wrong password warning

### ISSUE THREAD

**Issue by NoctusRex** [NoctusRex/SharpLocker-2.0#11]
Tell people that their password was wrong, so they try harder to type it right
- 1 or 2 times
- show windows login loading gif thing
- show error
- collect all entered passwords and give them into the now function

**Comment by Cyklan** [comment]
should be optional
also, amount of password enters should be random between 1 and 2

**Comment by NoctusRex** [comment]
Create parameter interface that is loaded at startup and can be customized the same way as the IDoBadStuff-interface?
-> Both classes that implement the interfaces can still be in the same .dll file
-> Parameter-interface could control different things like: Show wrong password warning, show it random times, min and max times, fixed amount of times
