### ISSUE TITLE
New Name

### ISSUE THREAD

**Issue by Cyklan** [NoctusRex/SharpLocker-2.0#15]
To be honest, SharpLocker 2.0 sounds kinda bland.
It needs a new, catchier name!

### Name Brainstorming Time

Ideas of mine (no particular order):

- Lokkit
- backet
- logine
- unl0ck
- unlockr
- passteal

**Comment by NoctusRex** [comment]
lock-out
lock-in

**Comment by Cyklan** [comment]
How about "windows 10 login"?
Clean and simple

**Comment by NoctusRex** [comment]
Windows 10 Lokk-In ?

**Comment by Cyklan** [comment]
Deal
