### ISSUE TITLE
Anti Virus detection

### ISSUE THREAD

**Issue by chikko80** [NoctusRex/SharpLocker-2.0#21]
Hey, i made a few adjustments for post request the pw and now its great. My problem is the antivirus detection. Every time i download the exe file from a webserver or something like this, my Avira Antivirus detects it as TR/Lockscreen and locks the execution. Is there any workaround or bypass? or does anyone facing the same problem?
Greetings

**Comment by NoctusRex** [comment]
Hey chikko,

I've got a few questions for you:

* Does this only happen when you download the application as .exe or .zip file from the internet?
  -> If you clone and build the application and then start it without download, will the same problem occur as well?

* Does only your anti virus software block the application or is windows blocking it as well?
  -> Try turning Avira off and then execute it.

* Did you try the same procedure on different PCs, if yes what did happen?

There is a thing called Windows Defender SmartScreen.
If you download a file fromthe internet, mail, etc. or unzipping a file with the windows zip-tool will cause the application to be marked as "Unknown" using a Zone-Identifier.

Avira might do a similar thing.

In that case you need to find a way to distribute the software using a different way.
Like a [bad usb](https://malduino.com/)

Another possible way to solve this problem could be to put the .exe-file into a different archive then .zip, like .rar or .7zip and unpacking these zip files with a different compressing tool then the windows .zip-Tool.

**Comment by chikko80** [comment]
Hey Noctus, I've now played around a bit, adjusted a few things and recompiled several times. Somehow that solved the problem. I can now easily download the script via powershell via rubber ducky command and run it without a problem with virus protection. Now another question: I already had the original SharpLocker script from Pickfordmatt. The old lockscreen (exe) started within a second of clicking. Your version, however, takes 8-10 seconds on my systems until the lockscreen appears. Is this normal or do I still have a mistake somewhere? I compile / build the app as normal with visual studio or directly via the msbuild command line. The waiting time occurs with DEBUG as well as with RELEASE build.

**Comment by NoctusRex** [comment]
Which version are you using?

We had some performance issues before this commit: 
* https://github.com/Lokk-In/SharpLocker-2.0/commit/a0856d1e73ca69772f3177bd9836e7eb8608b05a in the master branch
* https://github.com/Lokk-In/SharpLocker-2.0/commit/f419caf1bd19b305c2679bddedaf6722bee15045 in the develope branch

Make sure you are using a version that is higher or even then these commits.
On the systems I have tested the software on, it took no longer then 1 - 2 seconds to load.

If the problem still exitsts set a break point into the `Intialize()` function and check, using the F10 key, which step(s) is causing the problem. `InitializeUserLabel()` is known for taking some time.

```
        private void Initialize()
        {
            InitializeConfiguration();
            InitializeLanguage();
            InitializeMisc();
            InitializePasswordTextbox();
            InitializeKeyCombinations();
            InitializeUserLabel();
            InitializeUserIcon();
            InitializeBackground();
            InitializeBadStuff();
            InitializeOtherScreens();
            InitializeOtherUsers();
            InitializePasswordErrors();
        }
```

**Comment by Cyklan** [comment]
Original issue was resolved. Moving startup speed issue to new issue
