### ISSUE TITLE
Startup Speed Issue

### ISSUE THREAD

**Issue by Cyklan** [NoctusRex/SharpLocker-2.0#22]
Hey Noctus, I've now played around a bit, adjusted a few things and recompiled several times. Somehow that solved the problem. I can now easily download the script via powershell via rubber ducky command and run it without a problem with virus protection. Now another question: I already had the original SharpLocker script from Pickfordmatt. The old lockscreen (exe) started within a second of clicking. Your version, however, takes 8-10 seconds on my systems until the lockscreen appears. Is this normal or do I still have a mistake somewhere? I compile / build the app as normal with visual studio or directly via the msbuild command line. The waiting time occurs with DEBUG as well as with RELEASE build.

_Originally posted by @chikko80 in https://github.com/Lokk-In/SharpLocker-2.0/issues/21#issuecomment-584373749_

**Comment by Cyklan** [comment]
Which version are you using?
 
 We had some performance issues before this commit:
 
     * [a0856d1](https://github.com/Lokk-In/SharpLocker-2.0/commit/a0856d1e73ca69772f3177bd9836e7eb8608b05a) in the master branch
 
     * [f419caf](https://github.com/Lokk-In/SharpLocker-2.0/commit/f419caf1bd19b305c2679bddedaf6722bee15045) in the develope branch
 
 
 Make sure you are using a version that is higher or even then these commits.
 On the systems I have tested the software on, it took no longer then 1 - 2 seconds to load.
 
 If the problem still exitsts set a break point into the `Intialize()` function and check, using the F10 key, which step(s) is causing the problem. `InitializeUserLabel()` is known for taking some time.
 
 ```
         private void Initialize()
         {
             InitializeConfiguration();
             InitializeLanguage();
             InitializeMisc();
             InitializePasswordTextbox();
             InitializeKeyCombinations();
             InitializeUserLabel();
             InitializeUserIcon();
             InitializeBackground();
             InitializeBadStuff();
             InitializeOtherScreens();
             InitializeOtherUsers();
             InitializePasswordErrors();
         }
 ```

_originally posted by @NoctusRex in #21_

**Comment by chikko80** [comment]
So i checked a few things..
 1. i am on the latest master commit
 2. i debugged the init method and the problem seems to be at: UserNameLabel.Text = UserPrincipal.Current.DisplayName; in the InitializeUserLabel() method. This call takes about 11.5 seconds. Do you have any idea to fix this? 
oddly enough, it takes always exactly 11.5 seconds if UserPrincipal.Current.DisplayName is called


--- edit ---
tested it on my 2nd system and it worked fine without loading time. But on my main system (ryzen 5, 16gb ram) it takes about 11,5 seconds every time. I am very confused.
The problem I see here is that there are apparently computers on which the program loads for a long time, could be problematic in case.

**Comment by chikko80** [comment]
tested it on my 2nd system and it worked fine without loading time. But on my main system (ryzen 5, 16gb ram) it takes about 11,5 seconds every time. I am very confused. 
The problem I see here is that there are apparently computers on which the program loads for a long time, could be problematic in case.

**Comment by NoctusRex** [comment]
Sadly I have not found an other way to get the current user display name. 
I might make the method of acquiring the user name / display name configurable.
Maybe adding a timeout to that function could be a possibility as well.
